---
- name: Start
  hosts: localhost
  vars: 
    webserver_message: "I am running to the finish line."
  remote_user: Ansible
  gather_facts: false


  vars_files:
    - /etc/ansible/vars/info.yml

  tasks:
    - name: Find AMIs published by Red Hat (309956199498). Non-beta and x86
      ec2_ami_info:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        owners: 309956199498
        filters:
          architecture: x86_64
          name: RHEL-8*HVM-*
      register: amis

    #- name: Show AMI's
      #debug:
        #var: amis

    - name: Get the latest one
      set_fact:
        latest_ami: "{{ amis.images | sort(attribute='creation_date') | last }}"

    - name: Basic porvisioning of ec2 instance
      ec2:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        image: "{{ latest_ami.image_id }}"
        instance_type: t2.micro
        key_name: "{{ ssh_keyname }}"
        count: 1
        state: present
        group_id: sg-0a732c6cbeb3f1025
        wait: yes
        vpc_subnet_id: subnet-18872839 #172.31.80.0/20
        assign_public_ip: yes
        instance_tags:
          Name: new_demo_template
      register: ec2info
    
    #- name: Creating variable
      #var:
        #public_dns: ec2info.instances[0].public_dns_name
        
    - name: Print the results
      debug:
        var: ec2info.instance_ids[0]

    - name: Print the results
      debug:
        var: ec2info.instances[0].public_dns_name
        
    - name: Deploying Inventory
      template:
        src: templates/inventory.j2
        dest: /
        owner: hector
        group: hector
        mode: "0644"