---
- name: Start s
  hosts: ec2 #ec2
  gather_facts: false

  tasks:
    - name: Pinging
      ping:

    - name: Partitioning
      parted:
        device: "{{ item }}"
        number: 1
        state: present
        fs_type: ext4
      loop:
        - /dev/xvdf
        - /dev/xvdg
        - /dev/xvdh

    - name: Install lvm2 dependency
      package:
        name: lvm2
        state: present

    - name: Create VG
      lvg:
        vg: "{{ item.vg }}"
        pvs: "{{ item.pvs }}"
      loop:
        - { vg: 'vg-apps', pvs: '/dev/xvdf1'}
        - { vg: 'vg-logs', pvs: '/dev/xvdg1'}
        - { vg: 'vg-opt', pvs: '/dev/xvdh1'}

    - name: Create LV
      lvol:
        vg: "{{ item.vg }}"
        lv: "{{ item.lv }}"
        size: 100%FREE
      loop:
        - { vg: 'vg-apps', lv: 'lv-apps'}
        - { vg: 'vg-logs', lv: 'lv-logs'}
        - { vg: 'vg-opt', lv: 'lv-opt'}

    - name: Creating mounting directories
      file:
        path: "{{ item }}"
        state: directory
        owner: nobody
        mode: '0777'
      loop:
        - /mnt/apps
        - /mnt/logs
        - /mnt/opt

    - name: Format
      filesystem:
        fstype: xfs
        dev: "{{ item }}"
      loop:
        - /dev/vg-apps/lv-apps
        - /dev/vg-logs/lv-logs
        - /dev/vg-opt/lv-opt

    - name: Mount
      mount:
        path: "{{ item.dir}}"
        src: "{{ item.lv }}"
        fstype: xfs
        state: mounted
      loop:
        -  { dir: '/mnt/apps', lv: '/dev/vg-apps/lv-apps' }
        -  { dir: '/mnt/logs', lv: '/dev/vg-logs/lv-logs' }
        -  { dir: '/mnt/opt', lv: '/dev/vg-opt/lv-opt' }

    - name: fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ item }}"
      loop:
        - /dev/vg-apps/lv-apps /mnt/apps xfs defaults 0 0
        - /dev/vg-logs/lv-logs /mnt/logs xfs defaults 0 0
        - /dev/vg-opt/lv-opt /mnt/opt xfs defaults 0 0

    - name: daemon-reload
      systemd:
        daemon_reload: yes
