#Comibing Creation of EC2 with EBS attaching them, Configuring NFS 
---
- name: Start
  hosts: localhost
  remote_user: Ansible
  gather_facts: false

  vars_files:
    - /etc/ansible/vars/info.yml

  tasks:
    - name: Choosing subnet 172.31.80.0/20
      set_fact:
        subnet: subnet-18872839 
        
    - name: Getting Default VPC
      amazon.aws.ec2_vpc_net_info:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": Default
      register: default_vpc

    - name: Create Security Group NFS/DB
      ec2_group:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: "Project7"
        description: "Security Group for NFS/DB server"
        vpc_id: "{{ default_vpc.vpcs[0].vpc_id }}"
        rules:
          - proto: "tcp" 
            ports: "22" #remote using ssh
            cidr_ip: 0.0.0.0/0
          - proto: "udp"
            ports: "111" #used with NFS
            cidr_ip: 172.31.80.0/20
          - proto: "tcp"
            ports: "111" #used with NFS
            cidr_ip: 172.31.80.0/20
          - proto: "tcp"
            ports: "2049" #NFS
            cidr_ip: 172.31.80.0/20
          - proto: "tcp"
            ports: "3306" #MYSQL
            cidr_ip: 172.31.80.0/20
      register: Project7_NFS

    - name: Create Security Group web
      ec2_group:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: "Project7_web"
        description: "Security Group for NFS/DB server"
        vpc_id: "{{ default_vpc.vpcs[0].vpc_id }}"
        rules:
          - proto: "tcp" 
            ports: "22" #remote using ssh
            cidr_ip: 0.0.0.0/0
          - proto: "tcp"
            ports: "80" #http
            cidr_ip: 0.0.0.0/0
      register: Project7_web
        
    - name: Find AMIs published by Red Hat (309956199498). Non-beta and x86
      ec2_ami_info:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        owners: 309956199498
        filters:
          architecture: x86_64
          name: RHEL-8*HVM-*
      register: amis

    #- name: Show AMI's
      #debug
        #var: amis

    - name: Get the latest one
      set_fact:
        latest_ami: "{{ amis.images | sort(attribute='creation_date') | last }}"

    - name: Provisioning NFS/DB Server
      ec2:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        image: "{{ latest_ami.image_id }}"
        instance_type: t2.micro
        key_name: "{{ ssh_keyname }}"
        count: 1
        state: present
        group_id: "{{ Project7_NFS.group_id }}"
        wait: yes
        vpc_subnet_id: "{{ subnet }}" #172.31.80.0/20, needs to be dynamic
        assign_public_ip: yes
        instance_tags:
          Name: NFS
      register: ec2nfs

    #- name: Print the results
      #debug:
        #var: ec2nfs

    - name: Create EBS
      ec2_vol:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        volume_size: 10
        volume_type: gp2
        zone: us-east-1c
        delete_on_termination: true
        name: "{{ item.name }}"
        device_name: "{{ item.mapping }}"
        instance: "{{ ec2nfs.instance_ids[0] }}" 
        state: present
      loop:
        - { name: 'Project7Ansible1', mapping: '/dev/xvdf' }
        - { name: 'Project7Ansible2', mapping: '/dev/xvdg' }
        - { name: 'Project7Ansible3', mapping: '/dev/xvdh' }
      register: ansibleEBS

    #- name: debugEBS
      #debug:
        #var: ansibleEBS
        
    #Troubleshooting    
    # - name: Setting facts so that they will be persisted in the fact cache
      # set_fact:
        # privateIP: ec2nfs.instances[0].private_ip
    # - name: Output Private IP
      # debug:
        # var: "{{ privateIP }}"
    # - name: Output Private IP
      # ansible.builtin.debug:
        # msg: 'Trouble shooting IP string {{ ec2nfs.instances[0].private_ip }}'
        
    - name: WebServer
      ec2:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        image: "{{ latest_ami.image_id }}"
        instance_type: t2.micro
        key_name: "{{ ssh_keyname }}"
        count: 1 #number of instnaces to launch
        state: present
        group_id: "{{ Project7_web.group_id }}" 
        wait: yes
        vpc_subnet_id: "{{ subnet }}" #172.31.80.0/20, needs to be dynamic
        assign_public_ip: yes
        instance_tags:
          Name: web7 # 7 for project 7
      register: ec2web
 
    - name: Calling NFSconfigure
      command: ansible-playbook NFSconfigure.yml
      register: NFSconfigure
      
    - name: Output NFSconfigure
      debug:
        var: NFSconfigure   
      
    - name: Calling webConfigure
      command: ansible-playbook webConfigure.yml --extra-vars "privateIP={{ ec2nfs.instances[0].private_ip }}" 
      register: webConfigure

    - name: Output webConfigure
      debug:
        var: webConfigure 
        
        