- name: Configuring Web #Second Play
  hosts: _web7
  gather_facts: false
  remote_user: ec2-user

  vars_files:
    - vars/info.yml

  tasks:
    #- name: Settting NFS private IP variable
      #set_fact:
        #NFS_ip: {{ privateIP }} #<change IP of NFS, pending 
      
    - name: Pinging
      ping:
    
    - name: Install NFS client
      package:
        name: 
          - mysql
          - nfs-utils
          - nfs4-acl-tools
        state: present
#Need to turn on NFS

    #- name: fstab
      #lineinfile:
        #path: /etc/fstab
        #line: "{{ item }}"
      #loop:
        #- 172.31.81.122:/mnt/apps /var/www nfs defaults 0 0
        #- 172.31.81.122:/mnt/logs /var/log/httpd/ nfs defaults 0 0
        
    #this stopped working
    - name: Create www dir
      file:
        path: /var/www
        state: directory
        owner: nobody
        group: nobody
        mode: '0777'

    - name: Mount #fails if NFS server is not up
      ansible.posix.mount:
        path: /var/www
        src: "{{ privateIP }}:/mnt/apps" #NFS server PrivateIP
        fstype: nfs
        opts: rw,nosuid
        state: mounted #this mounts it
        
 #sudo mount -t nfs -o rw,nosuid 172.31.80.216:/mnt/apps /var/www 
 #sudo mount -t nfs -o rw,nosuid 172.31.88.22:/mnt/logs /var/log/httpd/

    - name: Install Apache
      package:
        name: httpd
        state: present  
        
    - name: Start Apache on boot
      ansible.builtin.service:
        name: httpd
        enabled: yes
        
    - name: Disable default site
      command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.backup
      
    - name: daemon-reload
      systemd:
        name: httpd
        state: started
        daemon_reload: yes
        
#sudo setenforce 0 need to fstab this

    - name: Disable SELinux #need to check if it remains after boot
      ansible.posix.selinux:
        state: disabled
      

    
    


