- name: Configuring Web #Second Play
  hosts: _web7
  gather_facts: false
  remote_user: ec2-user

  vars_files:
    - /etc/ansible/vars/info.yml

  tasks:
    - name: Pinging
      ping:
    
    - name: Install NFS client, mysql client
      package:
        name: 
          - mysql
          - nfs-utils
          - nfs4-acl-tools
        state: present
        
    - name: Installing php
      yum:
        enablerepo: "remi,remi-php80" 
        name:
         - php
         - php-gd
         - php-curl 
         - php-mysqlnd
         - php-mysqli
        state: latest

    - name: Create www dir
      file:
        path: /var/www
        state: directory
        owner: nobody
        group: nobody
        mode: '0777'

    - name: Mount #fails if NFS server is not up
      ansible.posix.mount:
        path: /var/www
        src: "{{ privateIP }}:/mnt/apps" #NFS server PrivateIP
        fstype: nfs
        opts: rw,nosuid
        state: mounted #this mounts it
        
    - name: Install Apache
      package:
        name: httpd
        state: present  
        
    - name: Start Apache on boot
      ansible.builtin.service:
        name: httpd
        enabled: yes
        
    - name: Disable default site
      command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.backup
      
    - name: daemon-reload
      systemd:
        name: httpd
        state: started
        daemon_reload: yes
        
#sudo setenforce 0 need to fstab this

    - name: Disable SELinux #need to check if it remains after boot
      ansible.posix.selinux:
        state: disabled
        
    


