- name: Configuring Database #Second Play
  hosts: _web7
  gather_facts: false
  remote_user: ec2-user

  vars_files:
    - vars/info.yml

  tasks:
    - name: Pinging
      ping:

    #maybe mounting shoudl be done first, create dirs, not really, no need to create dirs

    - name: Install NFS client
      package:
        name: 
          - mysql
          - nfs-utils
          - nfs4-acl-tools
          - git
        state: present
#Need to turn on NFS

    #- name: fstab
      #lineinfile:
        #path: /etc/fstab
        #line: "{{ item }}"
      #loop:
        #- 172.31.81.122:/mnt/apps /var/www nfs defaults 0 0
        #- 172.31.81.122:/mnt/logs /var/log/httpd/ nfs defaults 0 0
     
    - name: Create www dir
      file:
        path: /var/www
        state: directory
        owner: nobody
        group: nobody
        mode: '0777'
#mount manually here
    - name: Mount 
      ansible.posix.mount:
        path: /var/www
        src: 172.31.80.215:/mnt/apps #need to find a way to make this a var
        fstype: nfs
        opts: rw,nosuid
        state: mounted #this mounts it
    
    - name: daemon-reload
      systemd:
        daemon_reload: yes
        
    - name: Install Apache
      package:
        name: httpd
        state: present       
         
         
 #sudo mount -t nfs -o rw,nosuid 172.31.80.216:/mnt/apps /var/www 
 #sudo mount -t nfs -o rw,nosuid 172.31.88.22:/mnt/logs /var/log/httpd/
    
    
    #sudo mkdir /var/www install of httpds creates the dir


    #Mounted the httpd logs location to shared log folder with this command in the remote/webserver
    #sudo 

     
#maybe create the dir, before installation?
#3. Mount /var/www/ and target the NFS server’s export for apps
#sudo mkdir /var/www
#sudo mount -t nfs -o rw,nosuid <NFS-Server-Private-IP-Address>:/mnt/apps /var/www
#4. Verify that NFS was mounted successfully by running df -h. Make sure that the changes will persist on Web Server after reboot:
#sudo vi /etc/fstab
#add following line
#<NFS-Server-Private-IP-Address>:/mnt/apps /var/www nfs defaults 0 0
#5. Install Apache
#sudo yum install httpd -y
