
- name: Start Configuring
  hosts: _Jenkins9
  gather_facts: false
  remote_user: ec2-user

  vars_files:
    - /etc/ansible/vars/info.yml
    
  tasks:
    - name: Pinging
      ping:

    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

      #enalbe jeknins on boot
    - name: Install jenkins
      yum:
        name: 
          - jenkins
          - java-11-openjdk-devel
          - git
        state: latest
        
    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: yes
        
