- name: Start Configuring LB #Second Play
  hosts: _LB
  gather_facts: false
  remote_user: ubuntu

  vars_files:
    - /etc/ansible/vars/info.yml

  tasks:
    - name: Pinging
      ping:
      
    - name: Install a list of packages
      apt:
        update_cache : yes
        pkg:
        - apache2
        - libxml2-dev
        
    - name: Enable the Apache2 modules
      community.general.apache2_module:
        state: present
        name: "{{ item }}"
      loop:
        - rewrite
        - proxy
        - proxy_http
        - headers
        - lbmethod_bytraffic
      ignore_errors: yes  
      
    - name: 000-default.conf Backup
      ansible.builtin.copy:
        src: /etc/apache2/sites-available/000-default.conf
        dest: /etc/apache2/sites-available/000-default.confBAK
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        
    - name: Input Config File
      ansible.builtin.copy:
        src: LBconfigure
        dest: /etc/apache2/sites-available/000-default.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        
    - name: Restart apache2
      ansible.builtin.systemd:
        state: restarted
        name: apache2
      ignore_errors: yes  
